/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_gdv1394d (void)
{
  GtkWidget *gdv1394d;
  GtkWidget *vbox1;
//  GtkWidget *handlebox2;
  GtkWidget *hbox27;
  GtkWidget *vbox9;
//  GtkWidget *menubar;
//  GtkWidget *menuitem1;
//  GtkWidget *menuitem1_menu;
//  GtkWidget *item_connect;
//  GtkWidget *item_disconnect;
//  GtkWidget *separatormenuitem1;
//  GtkWidget *item_quit;
  GtkWidget *toolbar1;
  GtkWidget *tmp_toolbar_icon;
  GtkWidget *button_connect;
  GtkWidget *button_disconnect;
//  GtkWidget *vseparator1;
//  GtkWidget *button_quit;
  GtkWidget *hbox;
//  GtkWidget *toolbar2;
  GtkWidget *vbox6;
  GtkWidget *notebook1;
  GtkWidget *empty_notebook_page;
  GtkWidget *label40;
  GtkWidget *hbox20;
  GtkWidget *label46;
  GtkWidget *hbox16;
  GtkWidget *transport_0;
  GtkWidget *image19;
  GtkWidget *transport_1;
  GtkWidget *image18;
  GtkWidget *transport_2;
  GtkWidget *image17;
  GtkWidget *transport_3;
  GtkWidget *image12;
  GtkWidget *transport_4;
  GtkWidget *image11;
  GtkWidget *transport_5;
  GtkWidget *image9;
  GtkWidget *transport_6;
  GtkWidget *alignment9;
  GtkWidget *hbox17;
  GtkWidget *image10;
  GtkWidget *label41;
  GtkWidget *transport_7;
  GtkWidget *image13;
  GtkWidget *transport_8;
  GtkWidget *image14;
  GtkWidget *transport_9;
  GtkWidget *image15;
  GtkWidget *transport_10;
  GtkWidget *image16;
  GtkWidget *label47;
  GtkWidget *vbox_trim;
  GtkWidget *statusbar;

  gdv1394d = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (gdv1394d), _("Rugen"));
  gtk_window_set_default_size (GTK_WINDOW (gdv1394d), 640, 480);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (gdv1394d), vbox1);

//  handlebox2 = gtk_handle_box_new ();
//  gtk_widget_show (handlebox2);
//  gtk_box_pack_start (GTK_BOX (vbox1), handlebox2, FALSE, FALSE, 0);

  hbox27 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox27);
//  gtk_container_add (GTK_CONTAINER (handlebox2), hbox27);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox27, FALSE, FALSE, 0);

  vbox9 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox9);
  gtk_box_pack_start (GTK_BOX (hbox27), vbox9, TRUE, TRUE, 0);

//  menubar = gtk_menu_bar_new ();
//  gtk_widget_show (menubar);
//  gtk_box_pack_start (GTK_BOX (vbox9), menubar, TRUE, TRUE, 0);

//  menuitem1 = gtk_menu_item_new_with_mnemonic (_("_File"));
//  gtk_widget_show (menuitem1);
//  gtk_container_add (GTK_CONTAINER (menubar), menuitem1);

//  menuitem1_menu = gtk_menu_new ();
//  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem1), menuitem1_menu);

//  item_connect = gtk_menu_item_new_with_mnemonic (_("_Connect"));
//  gtk_widget_show (item_connect);
//  gtk_container_add (GTK_CONTAINER (menuitem1_menu), item_connect);

//  item_disconnect = gtk_menu_item_new_with_mnemonic (_("_Disconnect"));
//  gtk_widget_show (item_disconnect);
//  gtk_container_add (GTK_CONTAINER (menuitem1_menu), item_disconnect);

//  separatormenuitem1 = gtk_menu_item_new ();
//  gtk_widget_show (separatormenuitem1);
//  gtk_container_add (GTK_CONTAINER (menuitem1_menu), separatormenuitem1);
//  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

//  item_quit = gtk_menu_item_new_with_mnemonic (_("_Quit"));
//  gtk_widget_show (item_quit);
//  gtk_container_add (GTK_CONTAINER (menuitem1_menu), item_quit);

  toolbar1 = gtk_toolbar_new ();
  gtk_widget_show (toolbar1);
  gtk_box_pack_start (GTK_BOX (hbox27), toolbar1, TRUE, TRUE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_BOTH_HORIZ);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-connect", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1)));
  button_connect = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_TOGGLEBUTTON,
                                NULL,
                                "Connect",
                                _("Connect to a server"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar1)->children)->data))->label), TRUE);
  gtk_widget_show (button_connect);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-disconnect", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1)));
  button_disconnect = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_TOGGLEBUTTON,
                                NULL,
                                "Disconnect",
                                _("Disconnect from server"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar1)->children)->data))->label), TRUE);
  gtk_widget_show (button_disconnect);

  gtk_toolbar_append_space (GTK_TOOLBAR (toolbar1));

//  vseparator1 = gtk_vseparator_new ();
//  gtk_widget_show (vseparator1);
//  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar1), vseparator1, NULL, NULL);

//  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-quit", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1)));
//  button_quit = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
//                                GTK_TOOLBAR_CHILD_BUTTON,
//                                NULL,
//                                "",
//                                _("Exit"), NULL,
//                                tmp_toolbar_icon, NULL, NULL);
//  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar1)->children)->data))->label), TRUE);
//  gtk_widget_show (button_quit);

  hbox = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox, TRUE, TRUE, 0);

//  toolbar2 = gtk_toolbar_new ();
//  gtk_widget_show (toolbar2);
//  gtk_box_pack_start (GTK_BOX (hbox), toolbar2, FALSE, TRUE, 0);
//  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar2), GTK_TOOLBAR_BOTH);
//  gtk_toolbar_set_orientation (GTK_TOOLBAR (toolbar2), GTK_ORIENTATION_VERTICAL);

  vbox6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox6);
  gtk_box_pack_start (GTK_BOX (hbox), vbox6, TRUE, TRUE, 0);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (vbox6), notebook1, TRUE, TRUE, 0);
  GTK_WIDGET_UNSET_FLAGS (notebook1, GTK_CAN_FOCUS);
  gtk_notebook_set_show_tabs (GTK_NOTEBOOK (notebook1), FALSE);
  gtk_notebook_set_tab_pos (GTK_NOTEBOOK (notebook1), GTK_POS_RIGHT);
  gtk_notebook_popup_enable (GTK_NOTEBOOK (notebook1));
  gtk_notebook_set_show_border (GTK_NOTEBOOK (notebook1), FALSE);

  empty_notebook_page = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (empty_notebook_page);
  gtk_container_add (GTK_CONTAINER (notebook1), empty_notebook_page);

  label40 = gtk_label_new ("");
  gtk_widget_show (label40);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label40);
  gtk_label_set_justify (GTK_LABEL (label40), GTK_JUSTIFY_LEFT);

  hbox20 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox20);
  gtk_box_pack_start (GTK_BOX (vbox6), hbox20, FALSE, TRUE, 0);

  label46 = gtk_label_new ("");
  gtk_widget_show (label46);
  gtk_box_pack_start (GTK_BOX (hbox20), label46, TRUE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (label46), GTK_JUSTIFY_LEFT);

  hbox16 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox16);
  gtk_box_pack_start (GTK_BOX (hbox20), hbox16, FALSE, TRUE, 0);

  transport_0 = gtk_button_new ();
  gtk_widget_show (transport_0);
  gtk_box_pack_start (GTK_BOX (hbox16), transport_0, TRUE, FALSE, 0);
  gtk_widget_set_size_request (transport_0, 34, 25);
  GTK_WIDGET_UNSET_FLAGS (transport_0, GTK_CAN_FOCUS);
  gtk_button_set_relief (GTK_BUTTON (transport_0), GTK_RELIEF_NONE);
  gtk_widget_set_tooltip_text (transport_0, _("Beginning of playlist"));
  
  image19 = gtk_image_new_from_pixbuf( create_pixbuf ("stock_media-begin-16.png") );
  gtk_widget_show (image19);
  gtk_container_add (GTK_CONTAINER (transport_0), image19);

  transport_1 = gtk_button_new ();
  gtk_widget_show (transport_1);
  gtk_box_pack_start (GTK_BOX (hbox16), transport_1, TRUE, FALSE, 0);
  gtk_widget_set_size_request (transport_1, 34, 25);
  GTK_WIDGET_UNSET_FLAGS (transport_1, GTK_CAN_FOCUS);
  gtk_button_set_relief (GTK_BUTTON (transport_1), GTK_RELIEF_NONE);
  gtk_widget_set_tooltip_text (transport_1, _("Start of clip"));

  image18 = gtk_image_new_from_pixbuf( create_pixbuf ("stock_media-prev-16.png") );
  gtk_widget_show (image18);
  gtk_container_add (GTK_CONTAINER (transport_1), image18);

  transport_2 = gtk_button_new ();
  gtk_widget_show (transport_2);
  gtk_box_pack_start (GTK_BOX (hbox16), transport_2, TRUE, FALSE, 0);
  gtk_widget_set_size_request (transport_2, 34, 25);
  GTK_WIDGET_UNSET_FLAGS (transport_2, GTK_CAN_FOCUS);
  gtk_button_set_relief (GTK_BUTTON (transport_2), GTK_RELIEF_NONE);
  gtk_widget_set_tooltip_text (transport_2, _("Rewind"));

  image17 = gtk_image_new_from_pixbuf( create_pixbuf ("stock_media-rew-16.png") );
  gtk_widget_show (image17);
  gtk_container_add (GTK_CONTAINER (transport_2), image17);

  transport_3 = gtk_button_new ();
  gtk_widget_show (transport_3);
  gtk_box_pack_start (GTK_BOX (hbox16), transport_3, TRUE, FALSE, 0);
  gtk_widget_set_size_request (transport_3, 34, 25);
  GTK_WIDGET_UNSET_FLAGS (transport_3, GTK_CAN_FOCUS);
  gtk_button_set_relief (GTK_BUTTON (transport_3), GTK_RELIEF_NONE);
  gtk_widget_set_tooltip_text (transport_3, _("Previous frame"));

  image12 = gtk_image_new_from_pixbuf( create_pixbuf ("stock_media-prev-frame-16.png") );
  gtk_widget_show (image12);
  gtk_container_add (GTK_CONTAINER (transport_3), image12);

  transport_4 = gtk_button_new ();
  gtk_widget_show (transport_4);
  gtk_box_pack_start (GTK_BOX (hbox16), transport_4, TRUE, FALSE, 0);
  gtk_widget_set_size_request (transport_4, 34, 25);
  GTK_WIDGET_UNSET_FLAGS (transport_4, GTK_CAN_FOCUS);
  gtk_button_set_relief (GTK_BUTTON (transport_4), GTK_RELIEF_NONE);
  gtk_widget_set_tooltip_text (transport_4, _("Pause"));

  image11 = gtk_image_new_from_pixbuf( create_pixbuf ("stock_media-pause-16.png") );
  gtk_widget_show (image11);
  gtk_container_add (GTK_CONTAINER (transport_4), image11);

  transport_5 = gtk_button_new ();
  gtk_widget_show (transport_5);
  gtk_box_pack_start (GTK_BOX (hbox16), transport_5, TRUE, FALSE, 0);
  gtk_widget_set_size_request (transport_5, 34, 25);
  GTK_WIDGET_UNSET_FLAGS (transport_5, GTK_CAN_FOCUS);
  gtk_button_set_relief (GTK_BUTTON (transport_5), GTK_RELIEF_NONE);
  gtk_widget_set_tooltip_text (transport_5, _("Play"));

  image9 = gtk_image_new_from_pixbuf( create_pixbuf ("stock_media-play-16.png") );
  gtk_widget_show (image9);
  gtk_container_add (GTK_CONTAINER (transport_5), image9);

  transport_6 = gtk_button_new ();
  gtk_widget_show (transport_6);
  gtk_box_pack_start (GTK_BOX (hbox16), transport_6, TRUE, FALSE, 0);
  gtk_widget_set_size_request (transport_6, 34, 25);
  GTK_WIDGET_UNSET_FLAGS (transport_6, GTK_CAN_FOCUS);
  gtk_button_set_relief (GTK_BUTTON (transport_6), GTK_RELIEF_NONE);
  gtk_widget_set_tooltip_text (transport_6, _("Stop"));

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (transport_6), alignment9);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox17);

  image10 = gtk_image_new_from_pixbuf( create_pixbuf ("stock_media-stop-16.png") );
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox17), image10, FALSE, FALSE, 0);

  label41 = gtk_label_new_with_mnemonic ("");
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox17), label41, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label41), GTK_JUSTIFY_LEFT);

  transport_7 = gtk_button_new ();
  gtk_widget_show (transport_7);
  gtk_box_pack_start (GTK_BOX (hbox16), transport_7, TRUE, FALSE, 0);
  gtk_widget_set_size_request (transport_7, 34, 25);
  GTK_WIDGET_UNSET_FLAGS (transport_7, GTK_CAN_FOCUS);
  gtk_button_set_relief (GTK_BUTTON (transport_7), GTK_RELIEF_NONE);
  gtk_widget_set_tooltip_text (transport_7, _("Next frame"));

  image13 = gtk_image_new_from_pixbuf( create_pixbuf ("stock_media-next-frame-16.png") );
  gtk_widget_show (image13);
  gtk_container_add (GTK_CONTAINER (transport_7), image13);

  transport_8 = gtk_button_new ();
  gtk_widget_show (transport_8);
  gtk_box_pack_start (GTK_BOX (hbox16), transport_8, TRUE, FALSE, 0);
  gtk_widget_set_size_request (transport_8, 34, 25);
  GTK_WIDGET_UNSET_FLAGS (transport_8, GTK_CAN_FOCUS);
  gtk_button_set_relief (GTK_BUTTON (transport_8), GTK_RELIEF_NONE);
  gtk_widget_set_tooltip_text (transport_8, _("Fast forward"));

  image14 = gtk_image_new_from_pixbuf( create_pixbuf ("stock_media-fwd-16.png") );
  gtk_widget_show (image14);
  gtk_container_add (GTK_CONTAINER (transport_8), image14);

  transport_9 = gtk_button_new ();
  gtk_widget_show (transport_9);
  gtk_box_pack_start (GTK_BOX (hbox16), transport_9, TRUE, FALSE, 0);
  gtk_widget_set_size_request (transport_9, 34, 25);
  GTK_WIDGET_UNSET_FLAGS (transport_9, GTK_CAN_FOCUS);
  gtk_button_set_relief (GTK_BUTTON (transport_9), GTK_RELIEF_NONE);
  gtk_widget_set_tooltip_text (transport_9, _("Next clip"));

  image15 = gtk_image_new_from_pixbuf( create_pixbuf ("stock_media-next-16.png") );
  gtk_widget_show (image15);
  gtk_container_add (GTK_CONTAINER (transport_9), image15);

  transport_10 = gtk_button_new ();
  gtk_widget_show (transport_10);
  gtk_box_pack_start (GTK_BOX (hbox16), transport_10, TRUE, FALSE, 0);
  gtk_widget_set_size_request (transport_10, 34, 25);
  GTK_WIDGET_UNSET_FLAGS (transport_10, GTK_CAN_FOCUS);
  gtk_button_set_relief (GTK_BUTTON (transport_10), GTK_RELIEF_NONE);
  gtk_widget_set_tooltip_text (transport_10, _("End of playlist"));

  image16 = gtk_image_new_from_pixbuf( create_pixbuf ("stock_media-end-16.png") );
  gtk_widget_show (image16);
  gtk_container_add (GTK_CONTAINER (transport_10), image16);

  label47 = gtk_label_new ("");
  gtk_widget_show (label47);
  gtk_box_pack_start (GTK_BOX (hbox20), label47, TRUE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (label47), GTK_JUSTIFY_LEFT);

  vbox_trim = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox_trim);
  gtk_box_pack_start (GTK_BOX (vbox6), vbox_trim, FALSE, TRUE, 0);

  statusbar = gtk_statusbar_new ();
  gtk_widget_show (statusbar);
  gtk_box_pack_start (GTK_BOX (vbox1), statusbar, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gdv1394d, gdv1394d, "gdv1394d");
  GLADE_HOOKUP_OBJECT (gdv1394d, vbox1, "vbox1");
//  GLADE_HOOKUP_OBJECT (gdv1394d, handlebox2, "handlebox2");
  GLADE_HOOKUP_OBJECT (gdv1394d, hbox27, "hbox27");
  GLADE_HOOKUP_OBJECT (gdv1394d, vbox9, "vbox9");
//  GLADE_HOOKUP_OBJECT (gdv1394d, menubar, "menubar");
//  GLADE_HOOKUP_OBJECT (gdv1394d, menuitem1, "menuitem1");
//  GLADE_HOOKUP_OBJECT (gdv1394d, menuitem1_menu, "menuitem1_menu");
//  GLADE_HOOKUP_OBJECT (gdv1394d, item_connect, "item_connect");
//  GLADE_HOOKUP_OBJECT (gdv1394d, item_disconnect, "item_disconnect");
//  GLADE_HOOKUP_OBJECT (gdv1394d, separatormenuitem1, "separatormenuitem1");
//  GLADE_HOOKUP_OBJECT (gdv1394d, item_quit, "item_quit");
  GLADE_HOOKUP_OBJECT (gdv1394d, toolbar1, "toolbar1");
  GLADE_HOOKUP_OBJECT (gdv1394d, button_connect, "button_connect");
  GLADE_HOOKUP_OBJECT (gdv1394d, button_disconnect, "button_disconnect");
//  GLADE_HOOKUP_OBJECT (gdv1394d, vseparator1, "vseparator1");
//  GLADE_HOOKUP_OBJECT (gdv1394d, button_quit, "button_quit");
  GLADE_HOOKUP_OBJECT (gdv1394d, hbox, "hbox");
//  GLADE_HOOKUP_OBJECT (gdv1394d, toolbar2, "toolbar2");
  GLADE_HOOKUP_OBJECT (gdv1394d, vbox6, "vbox6");
  GLADE_HOOKUP_OBJECT (gdv1394d, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (gdv1394d, label40, "label40");
  GLADE_HOOKUP_OBJECT (gdv1394d, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (gdv1394d, label46, "label46");
  GLADE_HOOKUP_OBJECT (gdv1394d, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (gdv1394d, transport_0, "transport_0");
  GLADE_HOOKUP_OBJECT (gdv1394d, image19, "image19");
  GLADE_HOOKUP_OBJECT (gdv1394d, transport_1, "transport_1");
  GLADE_HOOKUP_OBJECT (gdv1394d, image18, "image18");
  GLADE_HOOKUP_OBJECT (gdv1394d, transport_2, "transport_2");
  GLADE_HOOKUP_OBJECT (gdv1394d, image17, "image17");
  GLADE_HOOKUP_OBJECT (gdv1394d, transport_3, "transport_3");
  GLADE_HOOKUP_OBJECT (gdv1394d, image12, "image12");
  GLADE_HOOKUP_OBJECT (gdv1394d, transport_4, "transport_4");
  GLADE_HOOKUP_OBJECT (gdv1394d, image11, "image11");
  GLADE_HOOKUP_OBJECT (gdv1394d, transport_5, "transport_5");
  GLADE_HOOKUP_OBJECT (gdv1394d, image9, "image9");
  GLADE_HOOKUP_OBJECT (gdv1394d, transport_6, "transport_6");
  GLADE_HOOKUP_OBJECT (gdv1394d, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (gdv1394d, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (gdv1394d, image10, "image10");
  GLADE_HOOKUP_OBJECT (gdv1394d, label41, "label41");
  GLADE_HOOKUP_OBJECT (gdv1394d, transport_7, "transport_7");
  GLADE_HOOKUP_OBJECT (gdv1394d, image13, "image13");
  GLADE_HOOKUP_OBJECT (gdv1394d, transport_8, "transport_8");
  GLADE_HOOKUP_OBJECT (gdv1394d, image14, "image14");
  GLADE_HOOKUP_OBJECT (gdv1394d, transport_9, "transport_9");
  GLADE_HOOKUP_OBJECT (gdv1394d, image15, "image15");
  GLADE_HOOKUP_OBJECT (gdv1394d, transport_10, "transport_10");
  GLADE_HOOKUP_OBJECT (gdv1394d, image16, "image16");
  GLADE_HOOKUP_OBJECT (gdv1394d, label47, "label47");
  GLADE_HOOKUP_OBJECT (gdv1394d, vbox_trim, "vbox_trim");
  GLADE_HOOKUP_OBJECT (gdv1394d, statusbar, "statusbar");

  return gdv1394d;
}

GtkWidget*
create_window_connection (void)
{
  GtkWidget *window_connection;
  GtkWidget *table2;
  GtkWidget *label30;
  GtkWidget *label31;
  GtkWidget *entry_server;
  GtkWidget *hbuttonbox4;
  GtkWidget *button_connect;
  GtkWidget *alignment2;
  GtkWidget *hbox8;
  GtkWidget *image2;
  GtkWidget *label32;
  GtkWidget *button_cancel;
  GtkWidget *alignment3;
  GtkWidget *hbox9;
  GtkWidget *image3;
  GtkWidget *label33;
  GtkWidget *hbox10;
  GtkWidget *entry_port;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  window_connection = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_connection), _("Connection"));
  gtk_window_set_position (GTK_WINDOW (window_connection), GTK_WIN_POS_MOUSE);
  gtk_window_set_modal (GTK_WINDOW (window_connection), TRUE);
  gtk_window_set_resizable (GTK_WINDOW (window_connection), FALSE);
  gtk_container_set_border_width (GTK_CONTAINER (window_connection), 8);
		
  table2 = gtk_table_new (3, 2, FALSE);
  gtk_widget_show (table2);
  gtk_container_add (GTK_CONTAINER (window_connection), table2);
  gtk_table_set_row_spacings (GTK_TABLE (table2), 8);
  gtk_table_set_col_spacings (GTK_TABLE (table2), 8);

  label30 = gtk_label_new (_("Server "));
  gtk_widget_show (label30);
  gtk_table_attach (GTK_TABLE (table2), label30, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label30), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label30), 0, 0.5);

  label31 = gtk_label_new (_("Port"));
  gtk_widget_show (label31);
  gtk_table_attach (GTK_TABLE (table2), label31, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label31), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label31), 0, 0.5);

  entry_server = gtk_entry_new ();
  gtk_widget_show (entry_server);
  gtk_table_attach (GTK_TABLE (table2), entry_server, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_entry_set_text (GTK_ENTRY (entry_server), _("localhost"));

  hbuttonbox4 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox4);
  gtk_table_attach (GTK_TABLE (table2), hbuttonbox4, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox4), GTK_BUTTONBOX_SPREAD);

  button_cancel = gtk_button_new ();
  gtk_widget_show (button_cancel);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), button_cancel);
  GTK_WIDGET_SET_FLAGS (button_cancel, GTK_CAN_DEFAULT);
  gtk_button_set_relief (GTK_BUTTON (button_cancel), GTK_RELIEF_NONE);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button_cancel), alignment3);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox9);

  image3 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox9), image3, FALSE, FALSE, 0);

  label33 = gtk_label_new_with_mnemonic (_("Cancel"));
  gtk_widget_show (label33);
  gtk_box_pack_start (GTK_BOX (hbox9), label33, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label33), GTK_JUSTIFY_LEFT);

  button_connect = gtk_button_new ();
  gtk_widget_show (button_connect);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), button_connect);
  GTK_WIDGET_SET_FLAGS (button_connect, GTK_CAN_DEFAULT);
  gtk_widget_add_accelerator (button_connect, "clicked", accel_group,
                              GDK_Return, 0,
                              GTK_ACCEL_VISIBLE);
  gtk_button_set_relief (GTK_BUTTON (button_connect), GTK_RELIEF_NONE);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button_connect), alignment2);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox8);

  image2 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox8), image2, FALSE, FALSE, 0);

  label32 = gtk_label_new_with_mnemonic (_("Connect"));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox8), label32, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label32), GTK_JUSTIFY_LEFT);

  hbox10 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox10);
  gtk_table_attach (GTK_TABLE (table2), hbox10, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  entry_port = gtk_entry_new ();
  gtk_widget_show (entry_port);
  gtk_box_pack_start (GTK_BOX (hbox10), entry_port, FALSE, TRUE, 0);
  gtk_entry_set_max_length (GTK_ENTRY (entry_port), 5);
  gtk_entry_set_text (GTK_ENTRY (entry_port), _("5250"));
  gtk_entry_set_width_chars (GTK_ENTRY (entry_port), 5);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_connection, window_connection, "window_connection");
  GLADE_HOOKUP_OBJECT (window_connection, table2, "table2");
  GLADE_HOOKUP_OBJECT (window_connection, label30, "label30");
  GLADE_HOOKUP_OBJECT (window_connection, label31, "label31");
  GLADE_HOOKUP_OBJECT (window_connection, entry_server, "entry_server");
  GLADE_HOOKUP_OBJECT (window_connection, hbuttonbox4, "hbuttonbox4");
  GLADE_HOOKUP_OBJECT (window_connection, button_connect, "button_connect");
  GLADE_HOOKUP_OBJECT (window_connection, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (window_connection, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (window_connection, image2, "image2");
  GLADE_HOOKUP_OBJECT (window_connection, label32, "label32");
  GLADE_HOOKUP_OBJECT (window_connection, button_cancel, "button_cancel");
  GLADE_HOOKUP_OBJECT (window_connection, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (window_connection, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (window_connection, image3, "image3");
  GLADE_HOOKUP_OBJECT (window_connection, label33, "label33");
  GLADE_HOOKUP_OBJECT (window_connection, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (window_connection, entry_port, "entry_port");

  gtk_widget_grab_default (button_connect);
  gtk_window_add_accel_group (GTK_WINDOW (window_connection), accel_group);

  return window_connection;
}

GtkWidget*
create_page_status (void)
{
  GtkWidget *page_status;
  GtkWidget *scrolledwindow4;
  GtkWidget *viewport1;
  GtkWidget *table3;
  GtkWidget *label_unit_0;
  GtkWidget *label_unit_1;
  GtkWidget *label_unit_2;
  GtkWidget *label_unit_3;
  GtkWidget *label_unit_4;
  GtkWidget *label_unit_5;
  GtkWidget *label_unit_6;
  GtkWidget *label_unit_7;
  GtkWidget *label_unit_8;
  GtkWidget *label_unit_9;
  GtkWidget *label_unit_10;
  GtkWidget *label_unit_11;
  GtkWidget *label_unit_13;
  GtkWidget *label_unit_14;
  GtkWidget *label_unit_15;
  GtkWidget *radiobutton_0;
  GSList *radiobutton_0_group = NULL;
  GtkWidget *radiobutton_1;
  GtkWidget *radiobutton_2;
  GtkWidget *radiobutton_3;
  GtkWidget *radiobutton_4;
  GtkWidget *radiobutton_5;
  GtkWidget *radiobutton_6;
  GtkWidget *radiobutton_7;
  GtkWidget *radiobutton_8;
  GtkWidget *radiobutton_9;
  GtkWidget *radiobutton_10;
  GtkWidget *radiobutton_11;
  GtkWidget *label_unit_12;
  GtkWidget *radiobutton_12;
  GtkWidget *radiobutton_13;
  GtkWidget *radiobutton_14;
  GtkWidget *radiobutton_15;

  page_status = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (page_status), _("page_status"));

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow4);
  gtk_container_add (GTK_CONTAINER (page_status), scrolledwindow4);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow4), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), viewport1);

  table3 = gtk_table_new (32, 1, FALSE);
  gtk_widget_show (table3);
  gtk_container_add (GTK_CONTAINER (viewport1), table3);

  label_unit_0 = gtk_label_new (_("00"));
  gtk_table_attach (GTK_TABLE (table3), label_unit_0, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label_unit_0), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label_unit_0), 0, 0.5);

  label_unit_1 = gtk_label_new (_("01"));
  gtk_table_attach (GTK_TABLE (table3), label_unit_1, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label_unit_1), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label_unit_1), 0, 0.5);

  label_unit_2 = gtk_label_new (_("02"));
  gtk_table_attach (GTK_TABLE (table3), label_unit_2, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label_unit_2), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label_unit_2), 0, 0.5);

  label_unit_3 = gtk_label_new (_("03"));
  gtk_table_attach (GTK_TABLE (table3), label_unit_3, 0, 1, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label_unit_3), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label_unit_3), 0, 0.5);

  label_unit_4 = gtk_label_new (_("04"));
  gtk_table_attach (GTK_TABLE (table3), label_unit_4, 0, 1, 9, 10,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label_unit_4), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label_unit_4), 0, 0.5);

  label_unit_5 = gtk_label_new (_("05"));
  gtk_table_attach (GTK_TABLE (table3), label_unit_5, 0, 1, 11, 12,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label_unit_5), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label_unit_5), 0, 0.5);

  label_unit_6 = gtk_label_new (_("06"));
  gtk_table_attach (GTK_TABLE (table3), label_unit_6, 0, 1, 13, 14,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label_unit_6), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label_unit_6), 0, 0.5);

  label_unit_7 = gtk_label_new (_("07"));
  gtk_table_attach (GTK_TABLE (table3), label_unit_7, 0, 1, 15, 16,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label_unit_7), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label_unit_7), 0, 0.5);

  label_unit_8 = gtk_label_new (_("08"));
  gtk_table_attach (GTK_TABLE (table3), label_unit_8, 0, 1, 17, 18,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label_unit_8), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label_unit_8), 0, 0.5);

  label_unit_9 = gtk_label_new (_("09"));
  gtk_table_attach (GTK_TABLE (table3), label_unit_9, 0, 1, 19, 20,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label_unit_9), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label_unit_9), 0, 0.5);

  label_unit_10 = gtk_label_new (_("10"));
  gtk_table_attach (GTK_TABLE (table3), label_unit_10, 0, 1, 21, 22,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label_unit_10), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label_unit_10), 0, 0.5);

  label_unit_11 = gtk_label_new (_("11"));
  gtk_table_attach (GTK_TABLE (table3), label_unit_11, 0, 1, 23, 24,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label_unit_11), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label_unit_11), 0, 0.5);

  label_unit_13 = gtk_label_new (_("13"));
  gtk_table_attach (GTK_TABLE (table3), label_unit_13, 0, 1, 27, 28,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label_unit_13), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label_unit_13), 0, 0.5);

  label_unit_14 = gtk_label_new (_("14"));
  gtk_table_attach (GTK_TABLE (table3), label_unit_14, 0, 1, 29, 30,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label_unit_14), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label_unit_14), 0, 0.5);

  label_unit_15 = gtk_label_new (_("15"));
  gtk_table_attach (GTK_TABLE (table3), label_unit_15, 0, 1, 31, 32,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label_unit_15), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label_unit_15), 0, 0.5);

  radiobutton_0 = gtk_radio_button_new_with_mnemonic (NULL, _("<disconnected>"));
  gtk_table_attach (GTK_TABLE (table3), radiobutton_0, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_0), radiobutton_0_group);
  radiobutton_0_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_0));

  radiobutton_1 = gtk_radio_button_new_with_mnemonic (NULL, _("<disconnected>"));
  gtk_table_attach (GTK_TABLE (table3), radiobutton_1, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_1), radiobutton_0_group);
  radiobutton_0_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_1));

  radiobutton_2 = gtk_radio_button_new_with_mnemonic (NULL, _("<disconnected>"));
  gtk_table_attach (GTK_TABLE (table3), radiobutton_2, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_2), radiobutton_0_group);
  radiobutton_0_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_2));

  radiobutton_3 = gtk_radio_button_new_with_mnemonic (NULL, _("<disconnected>"));
  gtk_table_attach (GTK_TABLE (table3), radiobutton_3, 0, 1, 6, 7,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_3), radiobutton_0_group);
  radiobutton_0_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_3));

  radiobutton_4 = gtk_radio_button_new_with_mnemonic (NULL, _("<disconnected>"));
  gtk_table_attach (GTK_TABLE (table3), radiobutton_4, 0, 1, 8, 9,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_4), radiobutton_0_group);
  radiobutton_0_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_4));

  radiobutton_5 = gtk_radio_button_new_with_mnemonic (NULL, _("<disconnected>"));
  gtk_table_attach (GTK_TABLE (table3), radiobutton_5, 0, 1, 10, 11,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_5), radiobutton_0_group);
  radiobutton_0_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_5));

  radiobutton_6 = gtk_radio_button_new_with_mnemonic (NULL, _("<disconnected>"));
  gtk_table_attach (GTK_TABLE (table3), radiobutton_6, 0, 1, 12, 13,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_6), radiobutton_0_group);
  radiobutton_0_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_6));

  radiobutton_7 = gtk_radio_button_new_with_mnemonic (NULL, _("<disconnected>"));
  gtk_table_attach (GTK_TABLE (table3), radiobutton_7, 0, 1, 14, 15,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_7), radiobutton_0_group);
  radiobutton_0_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_7));

  radiobutton_8 = gtk_radio_button_new_with_mnemonic (NULL, _("<disconnected>"));
  gtk_table_attach (GTK_TABLE (table3), radiobutton_8, 0, 1, 16, 17,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_8), radiobutton_0_group);
  radiobutton_0_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_8));

  radiobutton_9 = gtk_radio_button_new_with_mnemonic (NULL, _("<disconnected>"));
  gtk_table_attach (GTK_TABLE (table3), radiobutton_9, 0, 1, 18, 19,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_9), radiobutton_0_group);
  radiobutton_0_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_9));

  radiobutton_10 = gtk_radio_button_new_with_mnemonic (NULL, _("<disconnected>"));
  gtk_table_attach (GTK_TABLE (table3), radiobutton_10, 0, 1, 20, 21,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_10), radiobutton_0_group);
  radiobutton_0_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_10));

  radiobutton_11 = gtk_radio_button_new_with_mnemonic (NULL, _("<disconnected>"));
  gtk_table_attach (GTK_TABLE (table3), radiobutton_11, 0, 1, 22, 23,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_11), radiobutton_0_group);
  radiobutton_0_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_11));

  label_unit_12 = gtk_label_new (_("12"));
  gtk_table_attach (GTK_TABLE (table3), label_unit_12, 0, 1, 25, 26,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label_unit_12), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (label_unit_12), 0, 0.5);

  radiobutton_12 = gtk_radio_button_new_with_mnemonic (NULL, _("<disconnected>"));
  gtk_table_attach (GTK_TABLE (table3), radiobutton_12, 0, 1, 24, 25,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_12), radiobutton_0_group);
  radiobutton_0_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_12));

  radiobutton_13 = gtk_radio_button_new_with_mnemonic (NULL, _("<disconnected>"));
  gtk_table_attach (GTK_TABLE (table3), radiobutton_13, 0, 1, 26, 27,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_13), radiobutton_0_group);
  radiobutton_0_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_13));

  radiobutton_14 = gtk_radio_button_new_with_mnemonic (NULL, _("<disconnected>"));
  gtk_table_attach (GTK_TABLE (table3), radiobutton_14, 0, 1, 28, 29,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_14), radiobutton_0_group);
  radiobutton_0_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_14));

  radiobutton_15 = gtk_radio_button_new_with_mnemonic (NULL, _("<disconnected>"));
  gtk_table_attach (GTK_TABLE (table3), radiobutton_15, 0, 1, 30, 31,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_15), radiobutton_0_group);
  radiobutton_0_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_15));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (page_status, page_status, "page_status");
  GLADE_HOOKUP_OBJECT (page_status, scrolledwindow4, "scrolledwindow4");
  GLADE_HOOKUP_OBJECT (page_status, viewport1, "viewport1");
  GLADE_HOOKUP_OBJECT (page_status, table3, "table3");
  GLADE_HOOKUP_OBJECT (page_status, label_unit_0, "label_unit_0");
  GLADE_HOOKUP_OBJECT (page_status, label_unit_1, "label_unit_1");
  GLADE_HOOKUP_OBJECT (page_status, label_unit_2, "label_unit_2");
  GLADE_HOOKUP_OBJECT (page_status, label_unit_3, "label_unit_3");
  GLADE_HOOKUP_OBJECT (page_status, label_unit_4, "label_unit_4");
  GLADE_HOOKUP_OBJECT (page_status, label_unit_5, "label_unit_5");
  GLADE_HOOKUP_OBJECT (page_status, label_unit_6, "label_unit_6");
  GLADE_HOOKUP_OBJECT (page_status, label_unit_7, "label_unit_7");
  GLADE_HOOKUP_OBJECT (page_status, label_unit_8, "label_unit_8");
  GLADE_HOOKUP_OBJECT (page_status, label_unit_9, "label_unit_9");
  GLADE_HOOKUP_OBJECT (page_status, label_unit_10, "label_unit_10");
  GLADE_HOOKUP_OBJECT (page_status, label_unit_11, "label_unit_11");
  GLADE_HOOKUP_OBJECT (page_status, label_unit_13, "label_unit_13");
  GLADE_HOOKUP_OBJECT (page_status, label_unit_14, "label_unit_14");
  GLADE_HOOKUP_OBJECT (page_status, label_unit_15, "label_unit_15");
  GLADE_HOOKUP_OBJECT (page_status, radiobutton_0, "radiobutton_0");
  GLADE_HOOKUP_OBJECT (page_status, radiobutton_1, "radiobutton_1");
  GLADE_HOOKUP_OBJECT (page_status, radiobutton_2, "radiobutton_2");
  GLADE_HOOKUP_OBJECT (page_status, radiobutton_3, "radiobutton_3");
  GLADE_HOOKUP_OBJECT (page_status, radiobutton_4, "radiobutton_4");
  GLADE_HOOKUP_OBJECT (page_status, radiobutton_5, "radiobutton_5");
  GLADE_HOOKUP_OBJECT (page_status, radiobutton_6, "radiobutton_6");
  GLADE_HOOKUP_OBJECT (page_status, radiobutton_7, "radiobutton_7");
  GLADE_HOOKUP_OBJECT (page_status, radiobutton_8, "radiobutton_8");
  GLADE_HOOKUP_OBJECT (page_status, radiobutton_9, "radiobutton_9");
  GLADE_HOOKUP_OBJECT (page_status, radiobutton_10, "radiobutton_10");
  GLADE_HOOKUP_OBJECT (page_status, radiobutton_11, "radiobutton_11");
  GLADE_HOOKUP_OBJECT (page_status, label_unit_12, "label_unit_12");
  GLADE_HOOKUP_OBJECT (page_status, radiobutton_12, "radiobutton_12");
  GLADE_HOOKUP_OBJECT (page_status, radiobutton_13, "radiobutton_13");
  GLADE_HOOKUP_OBJECT (page_status, radiobutton_14, "radiobutton_14");
  GLADE_HOOKUP_OBJECT (page_status, radiobutton_15, "radiobutton_15");

  return page_status;
}

GtkWidget*
create_page_clips (void)
{
  GtkWidget *page_clips;
  GtkWidget *vbox8;
  GtkWidget *hbox26;
  GtkWidget *label_directory;
  GtkWidget *optionmenu1;
  GtkWidget *menu1;
  GtkWidget *mode_0;
  GtkWidget *mode_1;
  GtkWidget *mode_2;
  GtkWidget *mode_3;
  GtkWidget *hpaned1;
  GtkWidget *table1;
  GtkWidget *scrolledwindow1;
  GtkWidget *list_dir;
  GtkWidget *vpaned1;
  GtkWidget *table5;
  GtkWidget *scrolledwindow6;
  GtkWidget *list_clips;
  GtkWidget *table4;
  GtkWidget *scrolledwindow5;
  GtkWidget *treeview1;
  GtkWidget *alignment12;
  GtkWidget *hbox19;
  GtkWidget *label44;
  GtkWidget *button_clips_refresh;
  GtkWidget *alignment5;
  GtkWidget *hbox12;
  GtkWidget *image5;
  GtkWidget *label36;
  GtkWidget *button_clips_home;
  GtkWidget *alignment6;
  GtkWidget *hbox13;
  GtkWidget *image6;
  GtkWidget *label37;
  GtkWidget *button_up;
  GtkWidget *image21;
  GtkWidget *button_down;
  GtkWidget *image22;
  GtkWidget *button_remove;
  GtkWidget *image23;
  GtkWidget *button_clean;
  GtkWidget *image24;
  GtkWidget *hbuttonbox5;
  GtkWidget *label45;

  page_clips = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (page_clips), _("page_clips"));

  vbox8 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox8);
  gtk_container_add (GTK_CONTAINER (page_clips), vbox8);

  hbox26 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox26);
  gtk_box_pack_start (GTK_BOX (vbox8), hbox26, FALSE, FALSE, 0);

  label_directory = gtk_label_new (_("Disconnected"));
  gtk_widget_show (label_directory);
  gtk_box_pack_start (GTK_BOX (hbox26), label_directory, TRUE, TRUE, 0);
  gtk_misc_set_alignment (GTK_MISC (label_directory), 0, 0.5);

  optionmenu1 = gtk_option_menu_new ();
  gtk_widget_show (optionmenu1);
  gtk_box_pack_start (GTK_BOX (hbox26), optionmenu1, FALSE, FALSE, 0);
  GTK_WIDGET_UNSET_FLAGS (optionmenu1, GTK_CAN_FOCUS);

  menu1 = gtk_menu_new ();

  mode_0 = gtk_menu_item_new_with_mnemonic (_("Play"));
  gtk_widget_show (mode_0);
  gtk_container_add (GTK_CONTAINER (menu1), mode_0);

  mode_1 = gtk_menu_item_new_with_mnemonic (_("Load"));
  gtk_widget_show (mode_1);
  gtk_container_add (GTK_CONTAINER (menu1), mode_1);

  mode_2 = gtk_menu_item_new_with_mnemonic (_("Append"));
  gtk_widget_show (mode_2);
  gtk_container_add (GTK_CONTAINER (menu1), mode_2);

  mode_3 = gtk_menu_item_new_with_mnemonic (_("Insert"));
  gtk_widget_show (mode_3);
  gtk_container_add (GTK_CONTAINER (menu1), mode_3);

  gtk_option_menu_set_menu (GTK_OPTION_MENU (optionmenu1), menu1);

  hpaned1 = gtk_hpaned_new ();
  gtk_widget_show (hpaned1);
  gtk_box_pack_start (GTK_BOX (vbox8), hpaned1, TRUE, TRUE, 0);
  gtk_paned_set_position (GTK_PANED (hpaned1), 120);

  table1 = gtk_table_new (1, 1, FALSE);
  gtk_widget_show (table1);
  gtk_paned_pack1 (GTK_PANED (hpaned1), table1, FALSE, TRUE);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_table_attach (GTK_TABLE (table1), scrolledwindow1, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL), 0, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  list_dir = gtk_tree_view_new ();
  gtk_widget_show (list_dir);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), list_dir);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (list_dir), FALSE);

  vpaned1 = gtk_vpaned_new ();
  gtk_widget_show (vpaned1);
  gtk_paned_pack2 (GTK_PANED (hpaned1), vpaned1, TRUE, TRUE);
  gtk_paned_set_position (GTK_PANED (vpaned1), 130);

  table5 = gtk_table_new (1, 1, FALSE);
  gtk_widget_show (table5);
  gtk_paned_pack1 (GTK_PANED (vpaned1), table5, TRUE, TRUE);

  scrolledwindow6 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow6);
  gtk_table_attach (GTK_TABLE (table5), scrolledwindow6, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL), 0, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow6), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  list_clips = gtk_tree_view_new ();
  gtk_widget_show (list_clips);
  gtk_container_add (GTK_CONTAINER (scrolledwindow6), list_clips);
  gtk_tree_view_set_headers_visible (GTK_TREE_VIEW (list_clips), FALSE);
  gtk_tree_view_set_enable_search (GTK_TREE_VIEW (list_clips), FALSE);

  table4 = gtk_table_new (2, 1, FALSE);
  gtk_paned_pack2 (GTK_PANED (vpaned1), table4, TRUE, TRUE);

  scrolledwindow5 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow5);
  gtk_table_attach (GTK_TABLE (table4), scrolledwindow5, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_SHRINK | GTK_FILL), 0, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow5), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow5), treeview1);

  alignment12 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment12);
  gtk_table_attach (GTK_TABLE (table4), alignment12, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  hbox19 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox19);

  label44 = gtk_label_new (_(" "));
  gtk_widget_show (label44);
  gtk_box_pack_start (GTK_BOX (hbox19), label44, TRUE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (label44), GTK_JUSTIFY_LEFT);

  button_clips_refresh = gtk_button_new ();
  gtk_widget_show (button_clips_refresh);
  gtk_box_pack_start (GTK_BOX (hbox19), button_clips_refresh, FALSE, FALSE, 0);
  GTK_WIDGET_UNSET_FLAGS (button_clips_refresh, GTK_CAN_FOCUS);
  GTK_WIDGET_SET_FLAGS (button_clips_refresh, GTK_CAN_DEFAULT);
  gtk_button_set_relief (GTK_BUTTON (button_clips_refresh), GTK_RELIEF_NONE);
  gtk_widget_set_tooltip_text (button_clips_refresh, _("Refresh"));

  alignment5 = gtk_alignment_new (0, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button_clips_refresh), alignment5);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox12);

  image5 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox12), image5, FALSE, FALSE, 0);

  label36 = gtk_label_new_with_mnemonic ("");
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox12), label36, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label36), GTK_JUSTIFY_LEFT);

  button_clips_home = gtk_button_new ();
  gtk_widget_show (button_clips_home);
  gtk_box_pack_start (GTK_BOX (hbox19), button_clips_home, FALSE, FALSE, 0);
  GTK_WIDGET_UNSET_FLAGS (button_clips_home, GTK_CAN_FOCUS);
  GTK_WIDGET_SET_FLAGS (button_clips_home, GTK_CAN_DEFAULT);
  gtk_button_set_relief (GTK_BUTTON (button_clips_home), GTK_RELIEF_NONE);
  gtk_widget_set_tooltip_text (button_clips_home, _("Load root folder"));

  alignment6 = gtk_alignment_new (0, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button_clips_home), alignment6);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox13);

  image6 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox13), image6, FALSE, FALSE, 0);

  label37 = gtk_label_new_with_mnemonic ("");
  gtk_widget_show (label37);
  gtk_box_pack_start (GTK_BOX (hbox13), label37, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label37), GTK_JUSTIFY_LEFT);

  button_up = gtk_button_new ();
  gtk_widget_show (button_up);
  gtk_box_pack_start (GTK_BOX (hbox19), button_up, FALSE, FALSE, 0);
  GTK_WIDGET_UNSET_FLAGS (button_up, GTK_CAN_FOCUS);
  GTK_WIDGET_SET_FLAGS (button_up, GTK_CAN_DEFAULT);
  gtk_button_set_relief (GTK_BUTTON (button_up), GTK_RELIEF_NONE);
  gtk_widget_set_tooltip_text (button_up, _("Move current clip up"));

  image21 = gtk_image_new_from_stock ("gtk-go-up", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image21);
  gtk_container_add (GTK_CONTAINER (button_up), image21);

  button_down = gtk_button_new ();
  gtk_widget_show (button_down);
  gtk_box_pack_start (GTK_BOX (hbox19), button_down, FALSE, FALSE, 0);
  GTK_WIDGET_UNSET_FLAGS (button_down, GTK_CAN_FOCUS);
  GTK_WIDGET_SET_FLAGS (button_down, GTK_CAN_DEFAULT);
  gtk_button_set_relief (GTK_BUTTON (button_down), GTK_RELIEF_NONE);
  gtk_widget_set_tooltip_text (button_down, _("Move current clip down"));

  image22 = gtk_image_new_from_stock ("gtk-go-down", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image22);
  gtk_container_add (GTK_CONTAINER (button_down), image22);

  button_remove = gtk_button_new ();
  gtk_widget_show (button_remove);
  gtk_box_pack_start (GTK_BOX (hbox19), button_remove, FALSE, FALSE, 0);
  GTK_WIDGET_UNSET_FLAGS (button_remove, GTK_CAN_FOCUS);
  GTK_WIDGET_SET_FLAGS (button_remove, GTK_CAN_DEFAULT);
  gtk_button_set_relief (GTK_BUTTON (button_remove), GTK_RELIEF_NONE);
  gtk_widget_set_tooltip_text (button_remove, _("Remove current clip"));

  image23 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image23);
  gtk_container_add (GTK_CONTAINER (button_remove), image23);

  button_clean = gtk_button_new ();
  gtk_widget_show (button_clean);
  gtk_box_pack_start (GTK_BOX (hbox19), button_clean, FALSE, FALSE, 0);
  GTK_WIDGET_UNSET_FLAGS (button_clean, GTK_CAN_FOCUS);
  GTK_WIDGET_SET_FLAGS (button_clean, GTK_CAN_DEFAULT);
  gtk_button_set_relief (GTK_BUTTON (button_clean), GTK_RELIEF_NONE);
  gtk_widget_set_tooltip_text (button_clean, _("Remove all but current clip"));

  image24 = gtk_image_new_from_stock ("gtk-clear", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image24);
  gtk_container_add (GTK_CONTAINER (button_clean), image24);

  hbuttonbox5 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox5);
  gtk_box_pack_start (GTK_BOX (hbox19), hbuttonbox5, FALSE, FALSE, 0);

  label45 = gtk_label_new (_(" "));
  gtk_widget_show (label45);
  gtk_box_pack_start (GTK_BOX (hbox19), label45, TRUE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (label45), GTK_JUSTIFY_LEFT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (page_clips, page_clips, "page_clips");
  GLADE_HOOKUP_OBJECT (page_clips, vbox8, "vbox8");
  GLADE_HOOKUP_OBJECT (page_clips, hbox26, "hbox26");
  GLADE_HOOKUP_OBJECT (page_clips, label_directory, "label_directory");
  GLADE_HOOKUP_OBJECT (page_clips, optionmenu1, "optionmenu1");
  GLADE_HOOKUP_OBJECT (page_clips, menu1, "menu1");
  GLADE_HOOKUP_OBJECT (page_clips, mode_0, "mode_0");
  GLADE_HOOKUP_OBJECT (page_clips, mode_1, "mode_1");
  GLADE_HOOKUP_OBJECT (page_clips, mode_2, "mode_2");
  GLADE_HOOKUP_OBJECT (page_clips, mode_3, "mode_3");
  GLADE_HOOKUP_OBJECT (page_clips, hpaned1, "hpaned1");
  GLADE_HOOKUP_OBJECT (page_clips, table1, "table1");
  GLADE_HOOKUP_OBJECT (page_clips, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (page_clips, list_dir, "list_dir");
  GLADE_HOOKUP_OBJECT (page_clips, vpaned1, "vpaned1");
  GLADE_HOOKUP_OBJECT (page_clips, table5, "table5");
  GLADE_HOOKUP_OBJECT (page_clips, scrolledwindow6, "scrolledwindow6");
  GLADE_HOOKUP_OBJECT (page_clips, list_clips, "list_clips");
  GLADE_HOOKUP_OBJECT (page_clips, table4, "table4");
  GLADE_HOOKUP_OBJECT (page_clips, scrolledwindow5, "scrolledwindow5");
  GLADE_HOOKUP_OBJECT (page_clips, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (page_clips, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (page_clips, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (page_clips, label44, "label44");
  GLADE_HOOKUP_OBJECT (page_clips, button_clips_refresh, "button_clips_refresh");
  GLADE_HOOKUP_OBJECT (page_clips, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (page_clips, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (page_clips, image5, "image5");
  GLADE_HOOKUP_OBJECT (page_clips, label36, "label36");
  GLADE_HOOKUP_OBJECT (page_clips, button_clips_home, "button_clips_home");
  GLADE_HOOKUP_OBJECT (page_clips, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (page_clips, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (page_clips, image6, "image6");
  GLADE_HOOKUP_OBJECT (page_clips, label37, "label37");
  GLADE_HOOKUP_OBJECT (page_clips, button_up, "button_up");
  GLADE_HOOKUP_OBJECT (page_clips, image21, "image21");
  GLADE_HOOKUP_OBJECT (page_clips, button_down, "button_down");
  GLADE_HOOKUP_OBJECT (page_clips, image22, "image22");
  GLADE_HOOKUP_OBJECT (page_clips, button_remove, "button_remove");
  GLADE_HOOKUP_OBJECT (page_clips, image23, "image23");
  GLADE_HOOKUP_OBJECT (page_clips, button_clean, "button_clean");
  GLADE_HOOKUP_OBJECT (page_clips, image24, "image24");
  GLADE_HOOKUP_OBJECT (page_clips, hbuttonbox5, "hbuttonbox5");
  GLADE_HOOKUP_OBJECT (page_clips, label45, "label45");

  gtk_widget_grab_focus (list_dir);
  return page_clips;
}

GtkWidget*
create_page_shell (void)
{
  GtkWidget *page_shell;
  GtkWidget *vbox4;
  GtkWidget *hbox6;
  GtkWidget *label10;
  GtkWidget *entry_command;
  GtkWidget *button_command;
  GtkWidget *alignment7;
  GtkWidget *hbox14;
  GtkWidget *image7;
  GtkWidget *label38;
  GtkWidget *button_command_clear;
  GtkWidget *alignment8;
  GtkWidget *hbox15;
  GtkWidget *image8;
  GtkWidget *label39;
  GtkWidget *scrolledwindow3;
  GtkWidget *textview_command;
  GtkWidget *hbuttonbox3;

  page_shell = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (page_shell), _("page_shell"));

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox4);
  gtk_container_add (GTK_CONTAINER (page_shell), vbox4);

  hbox6 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox6);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox6, FALSE, TRUE, 0);

  label10 = gtk_label_new (_("Command "));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox6), label10, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label10), GTK_JUSTIFY_LEFT);

  entry_command = gtk_entry_new ();
  gtk_widget_show (entry_command);
  gtk_box_pack_start (GTK_BOX (hbox6), entry_command, TRUE, TRUE, 0);

  button_command = gtk_button_new ();
  gtk_widget_show (button_command);
  gtk_box_pack_start (GTK_BOX (hbox6), button_command, FALSE, FALSE, 0);
  GTK_WIDGET_SET_FLAGS (button_command, GTK_CAN_DEFAULT);
  gtk_button_set_relief (GTK_BUTTON (button_command), GTK_RELIEF_NONE);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button_command), alignment7);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox14);

  image7 = gtk_image_new_from_stock ("gtk-ok", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox14), image7, FALSE, FALSE, 0);

  label38 = gtk_label_new_with_mnemonic (_("_OK"));
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (hbox14), label38, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label38), GTK_JUSTIFY_LEFT);

  button_command_clear = gtk_button_new ();
  gtk_widget_show (button_command_clear);
  gtk_box_pack_start (GTK_BOX (hbox6), button_command_clear, FALSE, FALSE, 0);
  GTK_WIDGET_SET_FLAGS (button_command_clear, GTK_CAN_DEFAULT);
  gtk_button_set_relief (GTK_BUTTON (button_command_clear), GTK_RELIEF_NONE);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button_command_clear), alignment8);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox15);

  image8 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox15), image8, FALSE, FALSE, 0);

  label39 = gtk_label_new_with_mnemonic (_("Clear"));
  gtk_widget_show (label39);
  gtk_box_pack_start (GTK_BOX (hbox15), label39, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label39), GTK_JUSTIFY_LEFT);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow3);
  gtk_box_pack_start (GTK_BOX (vbox4), scrolledwindow3, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  textview_command = gtk_text_view_new ();
  gtk_widget_show (textview_command);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), textview_command);
  GTK_WIDGET_UNSET_FLAGS (textview_command, GTK_CAN_FOCUS);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (textview_command), FALSE);
  gtk_text_view_set_wrap_mode (GTK_TEXT_VIEW (textview_command), GTK_WRAP_WORD);
  gtk_text_view_set_cursor_visible (GTK_TEXT_VIEW (textview_command), FALSE);

  hbuttonbox3 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox3);
  gtk_box_pack_start (GTK_BOX (vbox4), hbuttonbox3, FALSE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox3), GTK_BUTTONBOX_SPREAD);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (page_shell, page_shell, "page_shell");
  GLADE_HOOKUP_OBJECT (page_shell, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (page_shell, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (page_shell, label10, "label10");
  GLADE_HOOKUP_OBJECT (page_shell, entry_command, "entry_command");
  GLADE_HOOKUP_OBJECT (page_shell, button_command, "button_command");
  GLADE_HOOKUP_OBJECT (page_shell, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (page_shell, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (page_shell, image7, "image7");
  GLADE_HOOKUP_OBJECT (page_shell, label38, "label38");
  GLADE_HOOKUP_OBJECT (page_shell, button_command_clear, "button_command_clear");
  GLADE_HOOKUP_OBJECT (page_shell, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (page_shell, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (page_shell, image8, "image8");
  GLADE_HOOKUP_OBJECT (page_shell, label39, "label39");
  GLADE_HOOKUP_OBJECT (page_shell, scrolledwindow3, "scrolledwindow3");
  GLADE_HOOKUP_OBJECT (page_shell, textview_command, "textview_command");
  GLADE_HOOKUP_OBJECT (page_shell, hbuttonbox3, "hbuttonbox3");

  gtk_widget_grab_default (button_command);
  return page_shell;
}

