/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_gdv1394d (void);
GtkWidget* create_window_connection (void);
GtkWidget* create_page_status (void);
GtkWidget* create_page_clips (void);
GtkWidget* create_page_shell (void);
